/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CidadaoRouteImport } from './routes/cidadao'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVisitasRouteImport } from './routes/app.visitas'
import { Route as AppTriagemRouteImport } from './routes/app.triagem'
import { Route as AppSessoesRouteImport } from './routes/app.sessoes'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppRecepcaoRouteImport } from './routes/app.recepcao'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppMeuPerfilRouteImport } from './routes/app.meu-perfil'
import { Route as AppHistoricoAtendimentosRouteImport } from './routes/app.historico-atendimentos'
import { Route as AppFilaRouteImport } from './routes/app.fila'
import { Route as AppDomiciliosRouteImport } from './routes/app.domicilios'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAgendasRouteImport } from './routes/app.agendas'
import { Route as AppAgendarRouteImport } from './routes/app.agendar'
import { Route as AppAgendaDiaRouteImport } from './routes/app.agenda-dia'
import { Route as AppVisitasIndexRouteImport } from './routes/app.visitas.index'
import { Route as AppDomiciliosIndexRouteImport } from './routes/app.domicilios.index'
import { Route as AppVisitasNovaRouteImport } from './routes/app.visitas.nova'
import { Route as AppDomiciliosNovoRouteImport } from './routes/app.domicilios.novo'
import { Route as AppDomiciliosIdRouteImport } from './routes/app.domicilios.$id'
import { Route as AppConfiguracoesSistemaRouteImport } from './routes/app.configuracoes.sistema'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoRoute = CidadaoRouteImport.update({
  id: '/cidadao',
  path: '/cidadao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitasRoute = AppVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagemRoute = AppTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AppRoute,
} as any)
const AppSessoesRoute = AppSessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRecepcaoRoute = AppRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuPerfilRoute = AppMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoAtendimentosRoute =
  AppHistoricoAtendimentosRouteImport.update({
    id: '/historico-atendimentos',
    path: '/historico-atendimentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppFilaRoute = AppFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AppRoute,
} as any)
const AppDomiciliosRoute = AppDomiciliosRouteImport.update({
  id: '/domicilios',
  path: '/domicilios',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendasRoute = AppAgendasRouteImport.update({
  id: '/agendas',
  path: '/agendas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendarRoute = AppAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaDiaRoute = AppAgendaDiaRouteImport.update({
  id: '/agenda-dia',
  path: '/agenda-dia',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitasIndexRoute = AppVisitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVisitasRoute,
} as any)
const AppDomiciliosIndexRoute = AppDomiciliosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDomiciliosRoute,
} as any)
const AppVisitasNovaRoute = AppVisitasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppVisitasRoute,
} as any)
const AppDomiciliosNovoRoute = AppDomiciliosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppDomiciliosRoute,
} as any)
const AppDomiciliosIdRoute = AppDomiciliosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDomiciliosRoute,
} as any)
const AppConfiguracoesSistemaRoute = AppConfiguracoesSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/verificar': typeof VerificarRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/domicilios': typeof AppDomiciliosRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app/triagem': typeof AppTriagemRoute
  '/app/visitas': typeof AppVisitasRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
  '/app/domicilios/$id': typeof AppDomiciliosIdRoute
  '/app/domicilios/novo': typeof AppDomiciliosNovoRoute
  '/app/visitas/nova': typeof AppVisitasNovaRoute
  '/app/domicilios/': typeof AppDomiciliosIndexRoute
  '/app/visitas/': typeof AppVisitasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/verificar': typeof VerificarRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app/triagem': typeof AppTriagemRoute
  '/app': typeof AppIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
  '/app/domicilios/$id': typeof AppDomiciliosIdRoute
  '/app/domicilios/novo': typeof AppDomiciliosNovoRoute
  '/app/visitas/nova': typeof AppVisitasNovaRoute
  '/app/domicilios': typeof AppDomiciliosIndexRoute
  '/app/visitas': typeof AppVisitasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/verificar': typeof VerificarRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/domicilios': typeof AppDomiciliosRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/meu-perfil': typeof AppMeuPerfilRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/recepcao': typeof AppRecepcaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app/triagem': typeof AppTriagemRoute
  '/app/visitas': typeof AppVisitasRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
  '/app/domicilios/$id': typeof AppDomiciliosIdRoute
  '/app/domicilios/novo': typeof AppDomiciliosNovoRoute
  '/app/visitas/nova': typeof AppVisitasNovaRoute
  '/app/domicilios/': typeof AppDomiciliosIndexRoute
  '/app/visitas/': typeof AppVisitasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/verificar'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/domicilios'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/meu-perfil'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app/triagem'
    | '/app/visitas'
    | '/app/'
    | '/api/public/version'
    | '/app/configuracoes/sistema'
    | '/app/domicilios/$id'
    | '/app/domicilios/novo'
    | '/app/visitas/nova'
    | '/app/domicilios/'
    | '/app/visitas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/verificar'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/meu-perfil'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app/triagem'
    | '/app'
    | '/api/public/version'
    | '/app/configuracoes/sistema'
    | '/app/domicilios/$id'
    | '/app/domicilios/novo'
    | '/app/visitas/nova'
    | '/app/domicilios'
    | '/app/visitas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/verificar'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/domicilios'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/meu-perfil'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app/triagem'
    | '/app/visitas'
    | '/app/'
    | '/api/public/version'
    | '/app/configuracoes/sistema'
    | '/app/domicilios/$id'
    | '/app/domicilios/novo'
    | '/app/visitas/nova'
    | '/app/domicilios/'
    | '/app/visitas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CidadaoRoute: typeof CidadaoRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  VerificarRoute: typeof VerificarRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao': {
      id: '/cidadao'
      path: '/cidadao'
      fullPath: '/cidadao'
      preLoaderRoute: typeof CidadaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visitas': {
      id: '/app/visitas'
      path: '/visitas'
      fullPath: '/app/visitas'
      preLoaderRoute: typeof AppVisitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/triagem': {
      id: '/app/triagem'
      path: '/triagem'
      fullPath: '/app/triagem'
      preLoaderRoute: typeof AppTriagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessoes': {
      id: '/app/sessoes'
      path: '/sessoes'
      fullPath: '/app/sessoes'
      preLoaderRoute: typeof AppSessoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recepcao': {
      id: '/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AppRecepcaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meu-perfil': {
      id: '/app/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/app/meu-perfil'
      preLoaderRoute: typeof AppMeuPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico-atendimentos': {
      id: '/app/historico-atendimentos'
      path: '/historico-atendimentos'
      fullPath: '/app/historico-atendimentos'
      preLoaderRoute: typeof AppHistoricoAtendimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fila': {
      id: '/app/fila'
      path: '/fila'
      fullPath: '/app/fila'
      preLoaderRoute: typeof AppFilaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domicilios': {
      id: '/app/domicilios'
      path: '/domicilios'
      fullPath: '/app/domicilios'
      preLoaderRoute: typeof AppDomiciliosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendas': {
      id: '/app/agendas'
      path: '/agendas'
      fullPath: '/app/agendas'
      preLoaderRoute: typeof AppAgendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendar': {
      id: '/app/agendar'
      path: '/agendar'
      fullPath: '/app/agendar'
      preLoaderRoute: typeof AppAgendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda-dia': {
      id: '/app/agenda-dia'
      path: '/agenda-dia'
      fullPath: '/app/agenda-dia'
      preLoaderRoute: typeof AppAgendaDiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visitas/': {
      id: '/app/visitas/'
      path: '/'
      fullPath: '/app/visitas/'
      preLoaderRoute: typeof AppVisitasIndexRouteImport
      parentRoute: typeof AppVisitasRoute
    }
    '/app/domicilios/': {
      id: '/app/domicilios/'
      path: '/'
      fullPath: '/app/domicilios/'
      preLoaderRoute: typeof AppDomiciliosIndexRouteImport
      parentRoute: typeof AppDomiciliosRoute
    }
    '/app/visitas/nova': {
      id: '/app/visitas/nova'
      path: '/nova'
      fullPath: '/app/visitas/nova'
      preLoaderRoute: typeof AppVisitasNovaRouteImport
      parentRoute: typeof AppVisitasRoute
    }
    '/app/domicilios/novo': {
      id: '/app/domicilios/novo'
      path: '/novo'
      fullPath: '/app/domicilios/novo'
      preLoaderRoute: typeof AppDomiciliosNovoRouteImport
      parentRoute: typeof AppDomiciliosRoute
    }
    '/app/domicilios/$id': {
      id: '/app/domicilios/$id'
      path: '/$id'
      fullPath: '/app/domicilios/$id'
      preLoaderRoute: typeof AppDomiciliosIdRouteImport
      parentRoute: typeof AppDomiciliosRoute
    }
    '/app/configuracoes/sistema': {
      id: '/app/configuracoes/sistema'
      path: '/sistema'
      fullPath: '/app/configuracoes/sistema'
      preLoaderRoute: typeof AppConfiguracoesSistemaRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesSistemaRoute: typeof AppConfiguracoesSistemaRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesSistemaRoute: AppConfiguracoesSistemaRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppDomiciliosRouteChildren {
  AppDomiciliosIdRoute: typeof AppDomiciliosIdRoute
  AppDomiciliosNovoRoute: typeof AppDomiciliosNovoRoute
  AppDomiciliosIndexRoute: typeof AppDomiciliosIndexRoute
}

const AppDomiciliosRouteChildren: AppDomiciliosRouteChildren = {
  AppDomiciliosIdRoute: AppDomiciliosIdRoute,
  AppDomiciliosNovoRoute: AppDomiciliosNovoRoute,
  AppDomiciliosIndexRoute: AppDomiciliosIndexRoute,
}

const AppDomiciliosRouteWithChildren = AppDomiciliosRoute._addFileChildren(
  AppDomiciliosRouteChildren,
)

interface AppVisitasRouteChildren {
  AppVisitasNovaRoute: typeof AppVisitasNovaRoute
  AppVisitasIndexRoute: typeof AppVisitasIndexRoute
}

const AppVisitasRouteChildren: AppVisitasRouteChildren = {
  AppVisitasNovaRoute: AppVisitasNovaRoute,
  AppVisitasIndexRoute: AppVisitasIndexRoute,
}

const AppVisitasRouteWithChildren = AppVisitasRoute._addFileChildren(
  AppVisitasRouteChildren,
)

interface AppRouteChildren {
  AppAgendaDiaRoute: typeof AppAgendaDiaRoute
  AppAgendarRoute: typeof AppAgendarRoute
  AppAgendasRoute: typeof AppAgendasRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppDomiciliosRoute: typeof AppDomiciliosRouteWithChildren
  AppFilaRoute: typeof AppFilaRoute
  AppHistoricoAtendimentosRoute: typeof AppHistoricoAtendimentosRoute
  AppMeuPerfilRoute: typeof AppMeuPerfilRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRecepcaoRoute: typeof AppRecepcaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSessoesRoute: typeof AppSessoesRoute
  AppTriagemRoute: typeof AppTriagemRoute
  AppVisitasRoute: typeof AppVisitasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaDiaRoute: AppAgendaDiaRoute,
  AppAgendarRoute: AppAgendarRoute,
  AppAgendasRoute: AppAgendasRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppDomiciliosRoute: AppDomiciliosRouteWithChildren,
  AppFilaRoute: AppFilaRoute,
  AppHistoricoAtendimentosRoute: AppHistoricoAtendimentosRoute,
  AppMeuPerfilRoute: AppMeuPerfilRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRecepcaoRoute: AppRecepcaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSessoesRoute: AppSessoesRoute,
  AppTriagemRoute: AppTriagemRoute,
  AppVisitasRoute: AppVisitasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CidadaoRoute: CidadaoRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  VerificarRoute: VerificarRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
