/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CidadaoRouteImport } from './routes/cidadao'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSessoesRouteImport } from './routes/app.sessoes'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppHistoricoAtendimentosRouteImport } from './routes/app.historico-atendimentos'
import { Route as AppFilaRouteImport } from './routes/app.fila'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAgendasRouteImport } from './routes/app.agendas'
import { Route as AppAgendarRouteImport } from './routes/app.agendar'
import { Route as AppAgendaDiaRouteImport } from './routes/app.agenda-dia'
import { Route as AppConfiguracoesSistemaRouteImport } from './routes/app.configuracoes.sistema'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoRoute = CidadaoRouteImport.update({
  id: '/cidadao',
  path: '/cidadao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessoesRoute = AppSessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoAtendimentosRoute =
  AppHistoricoAtendimentosRouteImport.update({
    id: '/historico-atendimentos',
    path: '/historico-atendimentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppFilaRoute = AppFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendasRoute = AppAgendasRouteImport.update({
  id: '/agendas',
  path: '/agendas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendarRoute = AppAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaDiaRoute = AppAgendaDiaRouteImport.update({
  id: '/agenda-dia',
  path: '/agenda-dia',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesSistemaRoute = AppConfiguracoesSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app': typeof AppIndexRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cidadao': typeof CidadaoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/app/agenda-dia': typeof AppAgendaDiaRoute
  '/app/agendar': typeof AppAgendarRoute
  '/app/agendas': typeof AppAgendasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/fila': typeof AppFilaRoute
  '/app/historico-atendimentos': typeof AppHistoricoAtendimentosRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sessoes': typeof AppSessoesRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/sistema': typeof AppConfiguracoesSistemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app/'
    | '/app/configuracoes/sistema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app'
    | '/app/configuracoes/sistema'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cidadao'
    | '/login'
    | '/painel'
    | '/app/agenda-dia'
    | '/app/agendar'
    | '/app/agendas'
    | '/app/auditoria'
    | '/app/configuracoes'
    | '/app/fila'
    | '/app/historico-atendimentos'
    | '/app/pacientes'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/sessoes'
    | '/app/'
    | '/app/configuracoes/sistema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CidadaoRoute: typeof CidadaoRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao': {
      id: '/cidadao'
      path: '/cidadao'
      fullPath: '/cidadao'
      preLoaderRoute: typeof CidadaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessoes': {
      id: '/app/sessoes'
      path: '/sessoes'
      fullPath: '/app/sessoes'
      preLoaderRoute: typeof AppSessoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico-atendimentos': {
      id: '/app/historico-atendimentos'
      path: '/historico-atendimentos'
      fullPath: '/app/historico-atendimentos'
      preLoaderRoute: typeof AppHistoricoAtendimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fila': {
      id: '/app/fila'
      path: '/fila'
      fullPath: '/app/fila'
      preLoaderRoute: typeof AppFilaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendas': {
      id: '/app/agendas'
      path: '/agendas'
      fullPath: '/app/agendas'
      preLoaderRoute: typeof AppAgendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendar': {
      id: '/app/agendar'
      path: '/agendar'
      fullPath: '/app/agendar'
      preLoaderRoute: typeof AppAgendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda-dia': {
      id: '/app/agenda-dia'
      path: '/agenda-dia'
      fullPath: '/app/agenda-dia'
      preLoaderRoute: typeof AppAgendaDiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/sistema': {
      id: '/app/configuracoes/sistema'
      path: '/sistema'
      fullPath: '/app/configuracoes/sistema'
      preLoaderRoute: typeof AppConfiguracoesSistemaRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesSistemaRoute: typeof AppConfiguracoesSistemaRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesSistemaRoute: AppConfiguracoesSistemaRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppRouteChildren {
  AppAgendaDiaRoute: typeof AppAgendaDiaRoute
  AppAgendarRoute: typeof AppAgendarRoute
  AppAgendasRoute: typeof AppAgendasRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppFilaRoute: typeof AppFilaRoute
  AppHistoricoAtendimentosRoute: typeof AppHistoricoAtendimentosRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSessoesRoute: typeof AppSessoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaDiaRoute: AppAgendaDiaRoute,
  AppAgendarRoute: AppAgendarRoute,
  AppAgendasRoute: AppAgendasRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppFilaRoute: AppFilaRoute,
  AppHistoricoAtendimentosRoute: AppHistoricoAtendimentosRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSessoesRoute: AppSessoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CidadaoRoute: CidadaoRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
